spring:
  profiles:
    group:
      "saturday": "localDB, saturday"
      "holiday": "localDB, holiday"
      "weekday": "localDB, weekday"

---

spring:
  config:
    activate:
      on-profile: "localDB"

  datasource:
    url: ${DATASOURCE_URL_LOCAL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      validation-query: select 1

---

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

---

service-key: ${SERVICE_KEY}

---

spring:
  batch:
    jdbc:
      initialize-schema: always

---

spring:
  batch:
    job:
      name: csvToDbJob
      enabled: false

---

spring:
  config:
    activate:
      on-profile: "saturday"

csv-file-path: "src/main/resources/station_time_table_saturday.csv"
log-file-path: "src/main/resources/station_time_table_saturday_log.csv"

---

spring:
  config:
    activate:
      on-profile: "holiday"

csv-file-path: "src/main/resources/station_time_table_holiday.csv"
log-file-path: "src/main/resources/station_time_table_holiday_log.csv"

---

spring:
  config:
    activate:
      on-profile: "weekday"

csv-file-path: "src/main/resources/station_time_table_weekday.csv"
log-file-path: "src/main/resources/station_time_table_weekday_log.csv"